### ISSUE TITLE
negremove II: The neg strikes back!

### ISSUE THREAD

**Issue by maximzakirov** [maximzakirov/capstoneproject#5]
**Here are the requirements for somebody assigned to this issue:**

- Changing toPlot to be lowercase so that it matches input function variable names
- Making negremove 2 and fingerprint clean the same function with an option to either do one pixel or the entire dataset
- Deciding negremove 2 to either have rotating code or have it just port the rotating functions instead and adding a comment that it doesn't need to have the dataset rotated beforehand.
- Commenting and cleaning the file

**Comment by mouselshamy** [comment]
Done
